[mypy]
# Ignora avisos de bibliotecas sem stubs de tipagem (FastAPI, Scipy, Pydantic, etc.)
ignore_missing_imports = True

# Define os caminhos onde o Mypy deve procurar seus módulos locais
mypy_path = Backend, Backend/api, Backend/pdr, Backend/filters

# Não falha em imports de módulos relativos
explicit_package_bases = True